### ISSUE TITLE
缺失区县

### ISSUE THREAD

**Issue by FaiChou** [OpenMarshall/KYDivisionPickerView#2]
注意 区县代码并不是不会以0结尾。

`if index.hasPrefix(cityNumPrefix) && !index.hasSuffix("0") {`

应该改为

`if index.hasPrefix(cityNumPrefix) && !index.hasSuffix("00") {`

**Comment by OpenMarshall** [comment]
fixed the problem [here](https://github.com/OpenMarshall/KYDivisionPickerView/commit/708361dd0a77b3e63204da26e487e1693b16e069)
